### ISSUE TITLE
Allow passing existing `Field`s to `fields`

### ISSUE THREAD

**Issue by jonathanj** [ClusterHQ/eliot#144]
As it stands combining previously defined `Field`s with `fields` is a bit of a mess:

```python
BAR = Field(u'bar', ...)
LOG_FOO = ActionType(u'example:foo', [BAR, ...] + fields(reason=int, ...), [BAR, ...] + fields(result=int), ...)
```

It would be convenient if `fields` accepted positional arguments of `Field` instances.

**Comment by mithrandi** [comment]
I think this can be closed now since #145 is merged.
