### ISSUE TITLE
Explain `task_level` structure in docs on Actions and Tasks

### ISSUE THREAD

**Issue by jml** [ClusterHQ/eliot#180]
The [Action and Tasks](http://eliot.readthedocs.org/en/0.7.1/actions.html#tasks-top-level-actions) document introduces the concepts that provide eliot with a tree structure (i.e. actions), but doesn't illustrate that tree structure. To get an illustration, you have to follow the link to the [Message Fields in Depth](http://eliot.readthedocs.org/en/0.7.1/fields.html). As a newcomer, it's easy to think that a document with "in depth" in the title isn't for you.

The next document after Actions and Tasks is about [Logging Across Processes and Threads](http://eliot.readthedocs.org/en/0.7.1/threads.html). That document assumes that you know what task levels are and how to read them.

#178 would mitigate this a little.

**Comment by itamarst** [comment]
OK, PR up for review, let me know what you think.
