### ISSUE TITLE
WrittenMessage and WrittenAction don't take plain Python objects

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/eliot#226]
WrittenAction and WrittenMessage take `UUID` for task_uuid and `pvector` for task_level in their tests. In real-world usage messages they will be parsing will have strings and lists respectively for those values.

**Comment by jml** [comment]
I think this is mostly a personal taste choice about where to draw the line.

`WrittenMessage.from_dict` explicitly takes a parsed log entry, on the assumption that there will be a separate layer to turn bytes into correct data structures.

**Comment by itamarst** [comment]
Well, I can see that for `task_uuid`, but `task_level` should be a `TaskLevel` in that case.

**Comment by jml** [comment]
Fair point!
